// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user_service.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCriterias int32

const (
	UserCriterias_FOO_UNSPECIFIED UserCriterias = 0
	UserCriterias_PHONE           UserCriterias = 1
	UserCriterias_CITY            UserCriterias = 2
	UserCriterias_HEIGHT          UserCriterias = 3
	UserCriterias_ISMARRIED       UserCriterias = 4
)

var UserCriterias_name = map[int32]string{
	0: "FOO_UNSPECIFIED",
	1: "PHONE",
	2: "CITY",
	3: "HEIGHT",
	4: "ISMARRIED",
}

var UserCriterias_value = map[string]int32{
	"FOO_UNSPECIFIED": 0,
	"PHONE":           1,
	"CITY":            2,
	"HEIGHT":          3,
	"ISMARRIED":       4,
}

func (x UserCriterias) String() string {
	return proto.EnumName(UserCriterias_name, int32(x))
}

func (UserCriterias) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e22b62bbe5b61e2e, []int{0}
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FName                string   `protobuf:"bytes,2,opt,name=fName,proto3" json:"fName,omitempty"`
	Height               float32  `protobuf:"fixed32,3,opt,name=Height,proto3" json:"Height,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Married              bool     `protobuf:"varint,6,opt,name=Married,proto3" json:"Married,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22b62bbe5b61e2e, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFName() string {
	if m != nil {
		return m.FName
	}
	return ""
}

func (m *User) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *User) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetMarried() bool {
	if m != nil {
		return m.Married
	}
	return false
}

// GetUserById Messages definations
type GetUserByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdRequest) Reset()         { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()    {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22b62bbe5b61e2e, []int{1}
}

func (m *GetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdRequest.Unmarshal(m, b)
}
func (m *GetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdRequest.Merge(m, src)
}
func (m *GetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdRequest.Size(m)
}
func (m *GetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdRequest proto.InternalMessageInfo

func (m *GetUserByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserByIdResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdResponse) Reset()         { *m = GetUserByIdResponse{} }
func (m *GetUserByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResponse) ProtoMessage()    {}
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22b62bbe5b61e2e, []int{2}
}

func (m *GetUserByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResponse.Unmarshal(m, b)
}
func (m *GetUserByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResponse.Merge(m, src)
}
func (m *GetUserByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResponse.Size(m)
}
func (m *GetUserByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResponse proto.InternalMessageInfo

func (m *GetUserByIdResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// GetUsersListByIds Messages definations
type GetUsersListByIdsRequest struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersListByIdsRequest) Reset()         { *m = GetUsersListByIdsRequest{} }
func (m *GetUsersListByIdsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersListByIdsRequest) ProtoMessage()    {}
func (*GetUsersListByIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22b62bbe5b61e2e, []int{3}
}

func (m *GetUsersListByIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersListByIdsRequest.Unmarshal(m, b)
}
func (m *GetUsersListByIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersListByIdsRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersListByIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersListByIdsRequest.Merge(m, src)
}
func (m *GetUsersListByIdsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersListByIdsRequest.Size(m)
}
func (m *GetUsersListByIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersListByIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersListByIdsRequest proto.InternalMessageInfo

func (m *GetUsersListByIdsRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetUsersListByIdsResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersListByIdsResponse) Reset()         { *m = GetUsersListByIdsResponse{} }
func (m *GetUsersListByIdsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersListByIdsResponse) ProtoMessage()    {}
func (*GetUsersListByIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22b62bbe5b61e2e, []int{4}
}

func (m *GetUsersListByIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersListByIdsResponse.Unmarshal(m, b)
}
func (m *GetUsersListByIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersListByIdsResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersListByIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersListByIdsResponse.Merge(m, src)
}
func (m *GetUsersListByIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersListByIdsResponse.Size(m)
}
func (m *GetUsersListByIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersListByIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersListByIdsResponse proto.InternalMessageInfo

func (m *GetUsersListByIdsResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// GetUserByCriteria Messages definations
type GetUsersByCriteriaRequest struct {
	Type                 UserCriterias `protobuf:"varint,1,opt,name=type,proto3,enum=protov3.UserCriterias" json:"type,omitempty"`
	Value                string        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetUsersByCriteriaRequest) Reset()         { *m = GetUsersByCriteriaRequest{} }
func (m *GetUsersByCriteriaRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersByCriteriaRequest) ProtoMessage()    {}
func (*GetUsersByCriteriaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22b62bbe5b61e2e, []int{5}
}

func (m *GetUsersByCriteriaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByCriteriaRequest.Unmarshal(m, b)
}
func (m *GetUsersByCriteriaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByCriteriaRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersByCriteriaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByCriteriaRequest.Merge(m, src)
}
func (m *GetUsersByCriteriaRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersByCriteriaRequest.Size(m)
}
func (m *GetUsersByCriteriaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByCriteriaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByCriteriaRequest proto.InternalMessageInfo

func (m *GetUsersByCriteriaRequest) GetType() UserCriterias {
	if m != nil {
		return m.Type
	}
	return UserCriterias_FOO_UNSPECIFIED
}

func (m *GetUsersByCriteriaRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetUsersByCriteriaResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersByCriteriaResponse) Reset()         { *m = GetUsersByCriteriaResponse{} }
func (m *GetUsersByCriteriaResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersByCriteriaResponse) ProtoMessage()    {}
func (*GetUsersByCriteriaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22b62bbe5b61e2e, []int{6}
}

func (m *GetUsersByCriteriaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByCriteriaResponse.Unmarshal(m, b)
}
func (m *GetUsersByCriteriaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByCriteriaResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersByCriteriaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByCriteriaResponse.Merge(m, src)
}
func (m *GetUsersByCriteriaResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersByCriteriaResponse.Size(m)
}
func (m *GetUsersByCriteriaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByCriteriaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByCriteriaResponse proto.InternalMessageInfo

func (m *GetUsersByCriteriaResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterEnum("protov3.UserCriterias", UserCriterias_name, UserCriterias_value)
	proto.RegisterType((*User)(nil), "protov3.User")
	proto.RegisterType((*GetUserByIdRequest)(nil), "protov3.GetUserByIdRequest")
	proto.RegisterType((*GetUserByIdResponse)(nil), "protov3.GetUserByIdResponse")
	proto.RegisterType((*GetUsersListByIdsRequest)(nil), "protov3.GetUsersListByIdsRequest")
	proto.RegisterType((*GetUsersListByIdsResponse)(nil), "protov3.GetUsersListByIdsResponse")
	proto.RegisterType((*GetUsersByCriteriaRequest)(nil), "protov3.GetUsersByCriteriaRequest")
	proto.RegisterType((*GetUsersByCriteriaResponse)(nil), "protov3.GetUsersByCriteriaResponse")
}

func init() {
	proto.RegisterFile("protos/user_service.proto", fileDescriptor_e22b62bbe5b61e2e)
}

var fileDescriptor_e22b62bbe5b61e2e = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6f, 0xda, 0x30,
	0x14, 0xc7, 0x97, 0x1f, 0x50, 0x78, 0x88, 0x2e, 0x7b, 0x9d, 0x2a, 0x97, 0xed, 0x90, 0xba, 0x3b,
	0x44, 0xd5, 0x44, 0x25, 0x7a, 0xd9, 0x71, 0x85, 0xd1, 0x26, 0xd2, 0x0a, 0xc8, 0xd0, 0xc3, 0x2a,
	0x55, 0x15, 0x5b, 0xbc, 0xd5, 0xd2, 0x56, 0x98, 0x6d, 0x90, 0xf8, 0x0f, 0x76, 0xde, 0x5f, 0x3c,
	0xd9, 0x49, 0x58, 0x69, 0x50, 0xa5, 0x9e, 0xec, 0x17, 0x7f, 0xde, 0xf7, 0xbd, 0xe7, 0xaf, 0x03,
	0x07, 0x73, 0x39, 0xd3, 0x33, 0x75, 0xb2, 0x50, 0x5c, 0xde, 0x2a, 0x2e, 0x97, 0xe2, 0x1b, 0x6f,
	0xdb, 0x6f, 0xb8, 0x63, 0x97, 0xe5, 0x29, 0xfd, 0xe3, 0x80, 0x7f, 0xa5, 0xb8, 0xc4, 0x5d, 0x70,
	0x45, 0x4a, 0x9c, 0xd0, 0x89, 0x3c, 0xe6, 0x8a, 0x14, 0x5f, 0x43, 0xe5, 0xfb, 0x60, 0xfa, 0x8b,
	0x13, 0x37, 0x74, 0xa2, 0x3a, 0xcb, 0x02, 0xdc, 0x87, 0x6a, 0xcc, 0xc5, 0x8f, 0x3b, 0x4d, 0xbc,
	0xd0, 0x89, 0x5c, 0x96, 0x47, 0x88, 0xe0, 0xf7, 0x84, 0x5e, 0x11, 0xdf, 0xc2, 0x76, 0x6f, 0x14,
	0x46, 0x77, 0xb3, 0x7b, 0x4e, 0x2a, 0x99, 0x82, 0x0d, 0x90, 0xc0, 0xce, 0xe5, 0x54, 0x4a, 0xc1,
	0x53, 0x52, 0x0d, 0x9d, 0xa8, 0xc6, 0x8a, 0x90, 0xbe, 0x03, 0xbc, 0xe0, 0xda, 0x34, 0xd3, 0x5d,
	0x25, 0x29, 0xe3, 0xbf, 0x17, 0x5c, 0xe9, 0xc7, 0x7d, 0xd1, 0x0f, 0xb0, 0xb7, 0x41, 0xa9, 0xf9,
	0xec, 0x5e, 0x71, 0x3c, 0x04, 0xdf, 0x8c, 0x69, 0xc1, 0x46, 0xa7, 0xd9, 0xce, 0xe7, 0x6b, 0x1b,
	0x90, 0xd9, 0x23, 0xfa, 0x1e, 0x48, 0x9e, 0xa9, 0x3e, 0x0b, 0xa5, 0x4d, 0xba, 0x2a, 0xaa, 0x04,
	0xe0, 0x89, 0x54, 0x11, 0x27, 0xf4, 0x22, 0x8f, 0x99, 0x2d, 0xfd, 0x08, 0x07, 0x5b, 0xe8, 0xbc,
	0xda, 0x11, 0x54, 0x8c, 0x64, 0x96, 0x50, 0x2a, 0x97, 0x9d, 0xd1, 0x9b, 0xff, 0x0a, 0xdd, 0x55,
	0x4f, 0x0a, 0xcd, 0xa5, 0x98, 0x16, 0x05, 0x8f, 0xc1, 0xd7, 0xab, 0x39, 0xb7, 0xfd, 0xee, 0x76,
	0xf6, 0x37, 0x04, 0x0a, 0x56, 0x31, 0xcb, 0x98, 0x8b, 0x5c, 0x4e, 0x7f, 0x2e, 0xd6, 0x56, 0xd8,
	0x80, 0x9e, 0x41, 0x6b, 0x9b, 0xfc, 0x33, 0x3a, 0x3c, 0x9e, 0x40, 0x73, 0xa3, 0x1e, 0xee, 0xc1,
	0xcb, 0xf3, 0xe1, 0xf0, 0xf6, 0x6a, 0x30, 0x1e, 0xf5, 0x7b, 0xc9, 0x79, 0xd2, 0xff, 0x14, 0xbc,
	0xc0, 0x3a, 0x54, 0x46, 0xf1, 0x70, 0xd0, 0x0f, 0x1c, 0xac, 0x81, 0xdf, 0x4b, 0x26, 0x5f, 0x02,
	0x17, 0x01, 0xaa, 0x71, 0x3f, 0xb9, 0x88, 0x27, 0x81, 0x87, 0x4d, 0xa8, 0x27, 0xe3, 0xcb, 0x33,
	0xc6, 0x0c, 0xef, 0x77, 0xfe, 0xba, 0xd0, 0x30, 0xb2, 0xe3, 0xec, 0xc5, 0x61, 0x0c, 0x8d, 0x07,
	0x8e, 0xe1, 0x9b, 0x75, 0x2b, 0x65, 0xb7, 0x5b, 0x6f, 0xb7, 0x1f, 0xe6, 0x43, 0x5d, 0xc3, 0xab,
	0x92, 0x27, 0x78, 0xf8, 0x38, 0xa5, 0xe4, 0x6e, 0x8b, 0x3e, 0x85, 0xe4, 0xda, 0x37, 0xeb, 0xd7,
	0xf7, 0xe0, 0x3a, 0xb1, 0x9c, 0x59, 0xb2, 0xb2, 0x75, 0xf4, 0x24, 0x93, 0xc9, 0x77, 0xe1, 0xba,
	0xd6, 0x3e, 0xc9, 0xfe, 0xc7, 0xaf, 0x55, 0xbb, 0x9e, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x75,
	0x34, 0xfb, 0x9a, 0xa0, 0x03, 0x00, 0x00,
}
